### ISSUE TITLE
Does not currently work with React Native.

### ISSUE THREAD

**Issue by frippera** [portabletext/react-portabletext#13]
Does not currently work with React Native. So no migration path of old implementation.

`const data = [
    {
      _key: "9ec013feda12",
      _type: "block",
      children: [
        {
          _key: "09308a7bb41d0",
          _type: "span",
          marks: [],
          text: "Some text here...",
        },
      ],
      markDefs: [],
      style: "normal",
    },
  ];`

OLD Implementation works fine
`<BlockContent
   blocks={data}
/>`

New
`<PortableText value={data} />`

Gives error
`Error: Text strings must be rendered within a <Text> component.

This error is located at:
    in strong (created by strong)
    in strong (created by ae)
    in p (created by normal)
    in normal (created by ae)
    in ae (created by ArticleDetailsScreen)
    in RCTView (created by View)
    in View (created by ArticleDetailsScreen)
    in RCTScrollContentView (created by ScrollView)
    in RCTScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by ArticleDetailsScreen)
    in RCTSafeAreaView
    in SafeAreaView (created by ArticleDetailsScreen)
    in ArticleDetailsScreen (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Screen)
    in MaybeFreeze (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by HomeStackNavigator)
    in HomeStackNavigator (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by BottomTabView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Screen)
    in MaybeFreeze (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
    in RNSScreenNavigationContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by BottomTabView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator (created by TabNavigator)
    in TabNavigator (created by RootNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by RootNavigator)
    in RootNavigator (created by App)
    in QueryClientProvider (created by ReactQueryProvider)
    in ReactQueryProvider (created by App)
    in AuthProvider (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in DevAppContainer (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0`

Tested with
"expo": "~44.0.0"
"react": "17.0.1",
"react-native": "0.64.3",
@portabletext/react": "^1.0.6"

**Comment by rexxars** [comment]
Very early days, but feel free to give https://github.com/portabletext/react-native-portabletext a try!
