### ISSUE TITLE
cannot override types block 

### ISSUE THREAD

**Issue by dukemai** [portabletext/react-portabletext#18]
it seems that the lib does not handle block customisation in types. I did like this

`types: {
		block: ({ children }) => {
			console.log("a");
			return <span>{children}</span>;
		},
     },`

and it does not do anything. I need to do in block part instead

**Comment by swalker326** [comment]
Do you have steps to reproduce this or a code sandbox demo?

**Comment by 88Navistar** [comment]
I'm having the same issue...I'm working off the examples in the documentation and can't access anything block.  Tried inside of "types" and outside as a standalone

**Comment by snorrees** [comment]
This should be fixed in [3.0.0](https://github.com/portabletext/react-portabletext/releases/tag/v3.0.0)
