### ISSUE TITLE
'React' is declared but its value is never read.

### ISSUE THREAD

**Issue by mckelveygreg** [portabletext/react-portabletext#20]
I am having a hard time using this library as it seems like I'm not picking up the build js files, but rather typescript is using the source files and having opinions about them! My `tsconfig.json` has `skipLibCheck: true`. It seems that it is not finding the correct export? I get the above error just by running `tsc --noEmit`

Right now my solution is to `patch` comment out the React references so my project will build.

I pulled down the repo to check things out. It looks like the tsconfig could be updated with `"jsx": "react-jsx"` as with React 17+, you no longer need to ghost import React to handle `jsx` and [they suggest moving away from it](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#removing-unused-react-imports). After updating the react eslint extends with "plugin:react/jsx-runtime" and removing the react import, all seemed well... 

Except I can't build because of linting errors in `react-portable-text.tsx` that exist on main... 

Are there settings I need to adjust on my end or can I help put up PR once the build issues get resolved?

**Comment by swalker326** [comment]
Do you have a code sandbox that reproduces this situation?

**Comment by mckelveygreg** [comment]
My bad! I was able to repro this by turning the tsconfig option `"noUnusedLocals": true`. This is a setting I'd like to keep on... 

Let me know if there is anything else I can do to this example to help! 

https://stackblitz.com/edit/vitejs-vite-askzne?file=tsconfig.json

**Comment by swalker326** [comment]
The example is throwing a different error than the one you mentioned. 

is this the error you mean? 

I'm also seeing an error on 

<img width="655" alt="image" src="https://user-images.githubusercontent.com/8460808/185795145-7afd36ad-ec78-4354-ae4f-aadac5b4fca3.png">

I'm also seeing an error on the PortableText import though, both are different than your original error. 

<img width="495" alt="image" src="https://user-images.githubusercontent.com/8460808/185795224-a9f58565-b5a7-46ad-9163-9a650980869b.png">

Is the project you're working in a vite project also?

**Comment by mckelveygreg** [comment]
Hmmm... that's bizarre. My error appears consistent. 
<img width="833" alt="image" src="https://user-images.githubusercontent.com/16110122/186782305-64a921e6-3f97-454a-ad46-0a6d54a600eb.png">

and yes, we have a vite project, pretty much like the stackblitz example

**Comment by gadkadosh** [comment]
I have the same problem with just plain `tsc`:

```
$ tsc --noEmit
node_modules/@portabletext/react/src/components/defaults.tsx:1:1 - error TS6133: 'React' is declared but its value is never read.

1 import React from 'react'
  ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@portabletext/react/src/components/list.tsx:1:1 - error TS6133: 'React' is declared but its value is never read.

1 import React from 'react'
  ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@portabletext/react/src/components/marks.tsx:2:1 - error TS6133: 'React' is declared but its value is never read.

2 import React from 'react'
  ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@portabletext/react/src/components/unknown.tsx:1:1 - error TS6133: 'React' is declared but its value is never read.

1 import React from 'react'
  ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@portabletext/react/src/react-portable-text.tsx:1:8 - error TS6133: 'React' is declared but its value is never read.

1 import React, {ReactNode, useContext, useMemo} from 'react'
```

The problem is probably the `d.ts` file in `dist` refers to `src` directory.

**Comment by mckelveygreg** [comment]
@swalker326 Sorry, just realized the React errors on `main.tsx` and I have no idea why not seems to be exportable from `@portabletext/react`... 

However, it still isn't building and I think @gadkadosh is right that the error is from the `d.ts` file referring `src` instead of some `dist` artifact

**Comment by mckelveygreg** [comment]
Closing as this appears to be fixed 🤷
