### ISSUE TITLE
Feature request: Tables

### ISSUE THREAD

**Issue by r3nanp** [portabletext/react-portabletext#25]
It would be nice to have table customization or configuration possible for it.

If someone have a solution for this, please let me know!!

**Comment by davydog187** [comment]
@r3nanp check out https://github.com/sanity-io/table. I'm also working on a version that supports PortableText for cells.

**Comment by r3nanp** [comment]
Hi @davydog187! Thanks for the answer. I'm looking forward to seeing PortableText support something like this, could you share the branch or fork that you are working on it?

**Comment by davydog187** [comment]
It's currently just on my laptop and will likely start as a new repo. I'll share when it's MVP ready in about two weeks time

**Comment by davydog187** [comment]
@r3nanp you should also close this issue as it has nothing to do with this repo. I just saw it by chance

**Comment by davydog187** [comment]
@r3nanp as promised, I just open sourced a table plugin with Portable Text support https://github.com/bitfo/sanity-portable-table

Please try it out and open an issue if you have feedback
