### ISSUE TITLE
Named export 'LIST_NEST_MODE_HTML' not found. 

### ISSUE THREAD

**Issue by tim-vw** [portabletext/react-portabletext#35]
Hi,

We have a Next JS project that is now failing to build due to the following error:

SyntaxError: Named export 'LIST_NEST_MODE_HTML' not found. The requested module '@portabletext/toolkit' is a CommonJS module

It seems to be related to the recent release, wondering if anyone else is having the issue and if there is a solution / work around?

Our project is a next/sanity build
next 12.3.1
yarn 3.2.1

Thanks Tim

**Comment by emmalevesque** [comment]
Was just running into this. Try running

```
yarn add -D @portabletext/react
```

**Comment by tim-vw** [comment]
Hey, thanks very much for that, it's regular dependency in our project rather than a dev dependency but running yarn add for the package has done it. 🙌
