### ISSUE TITLE
Can't do custom components

### ISSUE THREAD

**Issue by fostimus** [portabletext/react-portabletext#37]
Following the docs here: https://github.com/portabletext/react-portabletext#types

I have a field with `_type="testimonial"`, and when I have the following object for `components`, `PortableText` doesn't do anything.

```
const myPortableTextComponents = {
      block: {
        h1: headingHandler,
        h2: headingHandler,
        h3: headingHandler,
        h4: headingHandler,
        h5: headingHandler,
        h6: headingHandler,
      },
      types: {
        testimonial: (props) => {
          console.log(
            '\n\n\n\n**************\n** hey **\n**************\n\n\n\n'
          )

          console.log(props)
          return null
        },
      },
      testimonial: (props) => {
        console.log(
          '\n\n\n\n**************\n** hey **\n**************\n\n\n\n'
        )

        console.log(props)
        return null
      },
}

<PortableText
          value={node._rawContent}
          components={myPortableTextComponents}
        />
```

As you can see, I'm trying the `types` object and the top-level for the components object. Neither work.

**Comment by fostimus** [comment]
It appears that this is more of an issue with the docs not being updated accurately. To do custom components I had to do the following:
1. Not use `types` key at all. The docs incorrectly say to put `block` and any custom components underneath `types`, but it isn't used.
2. Use the `normal` key underneath the `block` key, which is top-level.
3. The React function for `normal` handles cases for custom components/types from Sanity.

My example with a custom 'testimonial' type:
```js
const myPortableTextComponents = {
      block: {
        h1: headingHandler,
        h2: headingHandler,
        h3: headingHandler,
        h4: headingHandler,
        h5: headingHandler,
        h6: headingHandler,
        normal: ({ children, node, ...others }) => {

          // TODO: testimonial value should come from sanity package!
          if (node?._type === 'testimonial') {
                      console.log(others, children)

            return null
          }

          return <p>{children}</p>
        },
      },
}
```

**Comment by kupe517** [comment]
@fostimus Thank you, that worked for me. 

There may be some kind of bug here. I noticed that the `types` way of doing it worked when my references weren't pulled into the GraphQL query. Once I pulled in the references using `_rawBody(resolveReferences: { maxDepth: 10 })` the types method was no longer seeing it and only @fostimus method worked.

**Comment by snorrees** [comment]
I am unfortunately unable to reproduce this. Please feel free to reopen, but make sure to include the JSON that you are passing to the PortableText component, so we can investigate further.
