### ISSUE TITLE
Cannot render embedded image

### ISSUE THREAD

**Issue by ImranSefat** [portabletext/react-portabletext#72]
I have a list of headings, body, images, etc. 

While rendering the block with the help of react-portabletext in a NEXT JS project with Typescript I don't see the image in the rendered HTML. After I have inspected it to look for the image, i see a div like below: 

`<div style="display:none">[@portabletext/react] Unknown block type "image", specify a component for it in the `components.types` prop</div>`

In the `PortableText` component I am using it like this below: 

`<PortableText
                value={data.body}
                onMissingComponent={false}
              />`

**Comment by KennedyNvsf** [comment]
Hey there, i encountered the same error, the image from the block content simply won't render.
Were you able to fix it ??

**Comment by ImranSefat** [comment]
@KennedyNvsf, thanks for reaching out. I have fixed this issue by defining the template. working fine now.
